AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool 用認証スタック（共通パラメータ参照）

Resources:

  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 
        - "${AppName}-${Environment}-UserPool"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: OPTIONAL
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true

  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 
        - "${AppName}-${Environment}-Client"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment
      UserPoolId: !Ref MyUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
        - USER_SRP_AUTH
      RefreshTokenValidity: 30

  MyUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 
        - "${AppName}-${Environment}-auth"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment
      UserPoolId: !Ref MyUserPool

Outputs:

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref MyUserPool
    Export:
      Name: !Sub 
        - "${AppName}-${Environment}-UserPoolId"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref MyUserPoolClient
    Export:
      Name: !Sub 
        - "${AppName}-${Environment}-UserPoolClientId"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment

  UserPoolDomain:
    Description: Cognito Hosted UI Domain
    Value: !Ref MyUserPoolDomain
    Export:
      Name: !Sub 
        - "${AppName}-${Environment}-UserPoolDomain"
        - AppName: !ImportValue Param-AppName
          Environment: !ImportValue Param-Environment
