AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool 用認証スタック

Parameters:
  AppName:
    Type: String
    Description: Application name
    Default: astra
  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-${Environment}-UserPool"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      MfaConfiguration: 'ON'
      Schema:
        - Name: email
          Required: true
          Mutable: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AppName}-${Environment}-Client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: true
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
        - USER_SRP_AUTH
      RefreshTokenValidity: 30

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AppName}-${Environment}-auth"
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "${AppName}-${Environment}-UserPoolId"

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "${AppName}-${Environment}-UserPoolClientId"

  UserPoolDomain:
    Description: Cognito Hosted UI Domain
    Value: !Ref CognitoUserPoolDomain
    Export:
      Name: !Sub "${AppName}-${Environment}-UserPoolDomain"