AWSTemplateFormatVersion: 2010-09-09
Description: Cognito User Pool

Parameters:
  DomainName:
    Type: String
    Description: Domain name for the callback URL
    Default: example.com
  AppName:
    Type: String
    Description: Application name
    Default: astra
  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-${Environment}-UserPool"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          Required: true
          Mutable: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AppName}-${Environment}-Client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      RefreshTokenValidity: 30

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AppName}-${Environment}-auth"
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolDomain:
    Description: Domain of the Cognito User Pool
    Value: !Sub ${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
  CallbackURL:
    Description: Callback URL for the Cognito User Pool Client
    Value: !Sub https://${DomainName}/oauth2/idpresponse